version: "3"

volumes:
  bul_volume:

services:
  app:
    build:
      dockerfile: ./Dockerfile
    tty: true
    depends_on:
      - postgres_service
    ports:
      - 8000:8000
    networks:
      - lognet

  postgres_service:
    image: postgres:14.5
    volumes:
      - bul_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
